nodeLinker: node-modules
yarnPath: .yarn/releases/yarn-3.5.0.cjs

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"

supportedArchitectures:
  cpu:
    - current
    - arm64
  os:
    - current
    - linux
