services:
  sandbox-vite:
    image: node:20-alpine
    command: 'npm run start'

    environment:
      NODE_ENV: 'development'
      VITE_CONTEMBER_ADMIN_API_BASE_URL: 'http://localhost:3001'
      VITE_CONTEMBER_ADMIN_SESSION_TOKEN: '0000000000000000000000000000000000000000'

    working_dir: /src/packages/admin-sandbox
    volumes:
      - .:/src:cached

  playground-vite:
    image: node:20-alpine
    command: 'npm run start'

    environment:
      NODE_ENV: 'development'
      VITE_CONTEMBER_ADMIN_API_BASE_URL: 'http://localhost:3001'
      VITE_CONTEMBER_ADMIN_SESSION_TOKEN: '0000000000000000000000000000000000000000'

    working_dir: /src/packages/playground
    volumes:
      - .:/src:cached

  playwright:
    image: node:20-alpine
    command: [ 'npm', 'run', 'pw:dev' ]
    user: '1000:1000'

    environment:
      CONTEMBER_API_URL: 'http://contember-engine:4000'
      VITE_CONTEMBER_ADMIN_SESSION_TOKEN: '0000000000000000000000000000000000000000'
      VITE_CONTEMBER_ADMIN_API_BASE_URL: 'http://localhost:3001'

    working_dir: /src/packages/admin
    volumes:
      - .:/src:cached

  playwright-tests:
    image: mcr.microsoft.com/playwright:v1.40.1-focal
    scale: 0
    command: [ 'sh' ]
    user: '1000:1000'

    environment:
      DISPLAY: ${DISPLAY}
      VITE_CONTEMBER_ADMIN_API_BASE_URL: 'http://playwright-contember-engine:4000'
      VITE_CONTEMBER_ADMIN_SESSION_TOKEN: '0000000000000000000000000000000000000000'

    working_dir: /src
    volumes:
      - .:/src:cached

  contember-engine:
    image: contember/engine:1.4.0-rc.1

    environment:
      NODE_ENV: 'development'

      CONTEMBER_PORT: '4000'
      CONTEMBER_ROOT_EMAIL: 'superadmin@localhost'
      CONTEMBER_ROOT_PASSWORD: 'superadmin@localhost'
      CONTEMBER_ROOT_TOKEN: '0000000000000000000000000000000000000000'
      CONTEMBER_LOGIN_TOKEN: '1111111111111111111111111111111111111111'
      CONTEMBER_ENCRYPTION_KEY: '0000000000000000000000000000000000000000000000000000000000000000'

      DEFAULT_DB_HOST: 'postgres'
      DEFAULT_DB_PORT: '5432'
      DEFAULT_DB_USER: 'contember'
      DEFAULT_DB_PASSWORD: 'contember'

      DEFAULT_S3_ENDPOINT: 'http://localhost:3003'
      DEFAULT_S3_PROVIDER: 'minio'
      DEFAULT_S3_REGION: ''
      DEFAULT_S3_BUCKET: 'contember'
      DEFAULT_S3_PREFIX: 'data'
      DEFAULT_S3_KEY: 'contember'
      DEFAULT_S3_SECRET: 'contember'

      TENANT_DB_NAME: 'tenant'

      TENANT_MAILER_HOST: 'mailhog'
      TENANT_MAILER_PORT: '1025'
      TENANT_MAILER_FROM: 'contember@localhost'
    healthcheck:
      test: 'curl --fail http://localhost:4000'
      interval: 5s
      timeout: 5s
      retries: 10

    depends_on:
      postgres:
        condition: service_healthy

  playwright-contember-engine:
    image: contember/engine:1.4.0-beta.1

    environment:
      NODE_ENV: 'development'

      CONTEMBER_PORT: '4000'
      CONTEMBER_ROOT_EMAIL: 'superadmin@localhost'
      CONTEMBER_ROOT_PASSWORD: 'superadmin@localhost'
      CONTEMBER_ROOT_TOKEN: '0000000000000000000000000000000000000000'
      CONTEMBER_LOGIN_TOKEN: '1111111111111111111111111111111111111111'
      CONTEMBER_ENCRYPTION_KEY: '0000000000000000000000000000000000000000000000000000000000000000'

      DEFAULT_DB_HOST: 'postgres'
      DEFAULT_DB_PORT: '5432'
      DEFAULT_DB_USER: 'contember'
      DEFAULT_DB_PASSWORD: 'contember'

      DEFAULT_S3_ENDPOINT: 'http://minio:9000'
      DEFAULT_S3_PROVIDER: 'minio'
      DEFAULT_S3_REGION: ''
      DEFAULT_S3_BUCKET: 'contember'
      DEFAULT_S3_PREFIX: 'data'
      DEFAULT_S3_KEY: 'contember'
      DEFAULT_S3_SECRET: 'contember'

      TENANT_DB_NAME: 'tenant-pw'

    healthcheck:
      test: 'curl --fail http://localhost:4000'
      interval: 5s
      timeout: 5s
      retries: 10

    depends_on:
      postgres:
        condition: service_healthy


  contember-cli:
    image: contember/cli:1.4.0-beta.1

    deploy:
      replicas: 0

    environment:
      CONTEMBER_SKIP_VERSION_CHECK: 1
      CONTEMBER_API_URL: 'http://contember-engine:4000/'
      CONTEMBER_API_TOKEN: '0000000000000000000000000000000000000000'

    volumes:
      - ./:/src

    depends_on:
      contember-engine:
        condition: service_healthy


  minio:
    image: bitnami/minio

    environment:
      MINIO_ROOT_USER: 'contember'
      MINIO_ROOT_PASSWORD: 'contember'
      MINIO_DEFAULT_BUCKETS: 'contember:download'

    volumes:
      - minio-data:/data:cached


  adminer:
    image: michalhosna/adminer:latest

    environment:
      ADMINER_DRIVER: pgsql
      ADMINER_SERVER: postgres
      ADMINER_DB: contember
      ADMINER_USERNAME: contember
      ADMINER_PASSWORD: contember
      ADMINER_AUTOLOGIN: 1
      ADMINER_NAME: Contember

    depends_on:
      - postgres


  postgres:
    image: postgres:13-alpine

    environment:
      POSTGRES_PASSWORD: contember
      POSTGRES_USER: contember
      POSTGRES_DB: contember

    volumes:
      - pgsql-data:/var/lib/postgresql/data

    healthcheck:
      test: 'pg_isready --username contember'
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 5s


  redis:
    image: redis:3.2-alpine

  mailhog:
    image: mailhog/mailhog
volumes:
  pgsql-data: ~
  minio-data: ~
